name: Validate PR description is not empty

on:
  pull_request:

jobs:
  check-description:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
    
    - name: Check PR description
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const pr = context.payload.pull_request;
          if (!pr || !pr.body || pr.body.trim().length === 0) {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: `
                ⚠️ **Пожалуйста, добавь описание к pull request.**

                Описание pull request помогает лучше понять изменения, которые вы вносите, облегчает процесс ревью и поиска причин инцидентов.
                Описание должно содержать **причину** изменений: какую **проблему** решаем, **зачем** делаем изменение, а не что изменилось.
                Причина может быть в описании issue или в треде, тогда достаточно указать ссылку.

                * Добавь ссылку на issue или тред, в котором раскрыта причина изменения
                * Если требуется, коротко опиши зачем делаешь изменение, какую проблему решаешь

                Спасибо!
              `.split('\n').map(line => line.trim()).join('\n')
            });
            throw new Error('Описание pull request не может быть пустым.');
          }

    # - name: Find Comment
    #   uses: peter-evans/find-comment@v3
    #   id: fc
    #   with:
    #     issue-number: ${{ github.event.pull_request.number }}
    #     comment-author: 'github-actions[bot]'
    #     body-includes: |
    #       ⚠️ **Пожалуйста, добавь описание к pull request.**
